### ISSUE TITLE
unit tests do not compile on Windows

### ISSUE THREAD

**Issue by vtorri** [luser-dr00g/xpost#38]
Make check on Windows leads to undefined symbols. Reason : memory and stack functions are not exported.

One possible solution : correctly define XPCHECKAPI in xpost_private.h:

#ifdef HAVE_CHECK
#define XPCHECKAPI XPAPI
#else
#define XPCHECKAPI
#endif

and declare/define functions used in unit tests with XPCHECKAPI

remarks ?

**Comment by luser-dr00g** [comment]
Ok. Does that handle the linking too? or just prototyping?

**Comment by vtorri** [comment]
Fixed in 76966b138fe9b4262da8b59db51c09dc1f6bea26 (with also previous commits)
