### ISSUE TITLE
[discussion] meson build system

### ISSUE THREAD

**Issue by vtorri** [luser-dr00g/xpost#49]
@luser-dr00g I would have to have your opinion to add a meson build system. It's hype, of course but it has several advantages compared to autotools or cmake

**Comment by luser-dr00g** [comment]
Sorry for the delay. I'm still reading up on it.

But by all means, bon chance!

**Comment by vtorri** [comment]
i have libxpost.dll built, but more work is needed for unix

**Comment by vtorri** [comment]
it's in, closing
